services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .docker/redis:/data
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: tasks
      MONGO_INITDB_ROOT_PASSWORD: tasks
      MONGO_INITDB_DATABASE: tasks
    ports:
      - "27017:27017"
    volumes:
      - .docker/mongo:/data/db
