FROM node:23.11.0-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

FROM node:23.11.0-alpine3.21 AS runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY . .

EXPOSE 4001

CMD ["node", "src/server.js"]



