### GET ALL
GET http://localhost:4001/api/v1/tasks

### FIND BY ID
GET http://localhost:4001/api/v1/tasks/c47a8534-ddd8-4a0b-a8cf-9c5e574e40e4

### CREATE TASK
POST http://localhost:4001/api/v1/tasks
Content-Type: application/json

{
  "title": "Task 2",
  "description": "This is task 2"
}

### UPDATE TASK
PUT http://localhost:4001/api/v1/tasks/b18e7568-19c8-434a-9fd4-58c0e8aadaf9
Content-Type: application/json

{
  "title": "Updated Task 1",
  "description": "This is the updated task 121"
}

### DELETE TASK
DELETE http://localhost:4001/api/v1/tasks/b18e7568-19c8-434a-9fd4-58c0e8aadaf9

### COMPLETE TASK
PATCH  http://localhost:4001/api/v1/tasks/b18e7568-19c8-434a-9fd4-58c0e8aadaf9/complete
Content-Type: application/json

### IMPORT FROM CSV
POST http://localhost:4001/api/v1/tasks/import
Content-Type: multipart/form-data
Content-Disposition: form-data; name="file"; filename="../tasks.csv"
Content-Type: text/csv
